import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Laberinto Estructura de datos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} 
        bg-[url('../public/img/bg1.webp')] bg-cover bg-center min-h-screen
        font-minecraft`}
      >
        {children}
      </body>
    </html>
  );
}
